VERSION = $(shell grep VERSION src/ssh_audit/globals.py | grep -E -o "'(v.*)'" | tr -d "'")
ifeq ($(VERSION),)
  $(error "could not determine version!")
endif

all:
	docker build -t positronsecurity/ssh-audit:${VERSION} .

upload:
	docker login
	docker buildx build \
		--platform linux/amd64,linux/arm64,linux/arm/v7 \
		--tag positronsecurity/ssh-audit:${VERSION} \
		--tag positronsecurity/ssh-audit:latest \
		--push \
		.
